[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = """
      default-src 'self'; 
      script-src 'self' 'unsafe-inline' 'unsafe-eval' https://cdnjs.cloudflare.com; 
      style-src 'self' 'unsafe-inline' https://cdnjs.cloudflare.com; 
      img-src 'self' data: https://ftp.goit.study; 
      font-src 'self' data:; 
      frame-ancestors 'none'; 
      connect-src 'self' https://so-yummy-app-backend-9mvu.vercel.app;
    """
    Permissions-Policy = "geolocation=(), microphone=()"

[[redirects]]
from = "/robots.txt"
to = "/robots.txt"
status = 200

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
