# ✅ Nagłówki HTTP dla lepszego bezpieczeństwa i obsługi pliku robots.txt
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://cdnjs.cloudflare.com; style-src 'self' 'unsafe-inline' https://cdnjs.cloudflare.com; img-src 'self' data:; font-src 'self' data:; frame-ancestors 'none'; connect-src 'self' https://so-yummy-app-backend-9mvu.vercel.app;"
    Permissions-Policy = "geolocation=(), microphone=()"



# ✅ Nagłówki dla robots.txt
[[headers]]
  for = "/robots.txt"
  [headers.values]
    Content-Type = "text/plain"

# ✅ Przekierowanie dla robots.txt, aby upewnić się, że jest dostępny
[[redirects]]
  from = "/robots.txt"
  to = "/robots.txt"
  status = 200
  force = true

# ✅ Przekierowanie wszystkich innych zapytań do index.html (Single Page App - SPA)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
