[[headers]]
for = "/*"
[headers.values]
X-Frame-Options = "DENY"
X-Content-Type-Options = "nosniff"
Referrer-Policy = "strict-origin-when-cross-origin"
  Content-Security-Policy = """
    default-src 'self';
    script-src 'self' 'unsafe-inline' https://cdnjs.cloudflare.com;
    style-src 'self' 'unsafe-inline' https://fonts.googleapis.com https://cdnjs.cloudflare.com;
    img-src 'self' data: https://ftp.goit.study;
    font-src 'self' https://fonts.gstatic.com;
    connect-src 'self' https://so-yummy-app-backend-9mvu.vercel.app;
    frame-ancestors 'none';
    base-uri 'self';
    form-action 'self';
  """


[[redirects]]
from = "/robots.txt"
to = "/robots.txt"
status = 200

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
