import { jsx as _jsx, jsxs as _jsxs, Fragment as _Fragment } from "react/jsx-runtime";
import css from "./Footer.module.css";
import logoFooter from "../../images/logoFooter.png";
import Nav from "./Nav/Nav";
import SubscribeForm from "./SubscribeForm/SubscribeForm";
import FollowUs from "./FollowUs/FollowUs";
import Media from "react-media";
const Footer = () => {
    return (_jsx(Media, { queries: {
            small: "(max-width: 768px)",
            medium: "(min-width: 768px) and (max-width: 1200px)",
            large: "(min-width: 1200px)",
        }, children: (matches) => (_jsxs(_Fragment, { children: [matches.small && (_jsx("footer", { className: css.footer, children: _jsxs("div", { className: css.container, children: [_jsxs("div", { className: css.logoBox, children: [_jsx("img", { src: logoFooter, alt: "logo", width: "30", height: "30", className: css.logo }), _jsx("p", { className: css.titleBox, children: "So Yummy" })] }), _jsxs("nav", { className: css.footerNav, children: [_jsx(Nav, {}), _jsx(SubscribeForm, {}), _jsx(FollowUs, {})] })] }) })), matches.medium && (_jsx("footer", { className: css.footer, children: _jsxs("div", { className: css.container, children: [_jsxs("div", { className: css.footerBox, children: [_jsxs("div", { className: css.footerBoxAssaid, children: [_jsxs("div", { className: css.logoBox, children: [_jsx("img", { src: logoFooter, alt: "logo", width: "30", height: "30", className: css.logo }), _jsx("p", { className: css.titleBox, children: "So Yummy" })] }), _jsxs("ul", { className: css.list, children: [_jsxs("li", { className: css.listItem, children: ["Database of recipes that can be replenished", " "] }), _jsx("li", { className: css.listItem, children: "Flexible search for desired and unwanted ingredients" }), _jsx("li", { className: css.listItem, children: "Ability to add your own recipes with photos" }), _jsx("li", { className: css.listItem, children: "Convenient and easy to use" })] })] }), _jsx("nav", { className: css.footerNav, children: _jsx(Nav, {}) })] }), _jsx(SubscribeForm, {}), _jsx(FollowUs, {})] }) })), matches.large && (_jsx("footer", { className: css.footer, children: _jsxs("div", { className: css.container, children: [_jsxs("div", { className: css.footerBox, children: [_jsxs("div", { className: css.footerBoxAssaid, children: [_jsxs("div", { className: css.logoBox, children: [_jsx("img", { src: logoFooter, alt: "logo", width: "30", height: "30", className: css.logo }), _jsx("p", { className: css.titleBox, children: "So Yummy" })] }), _jsxs("ul", { className: css.list, children: [_jsxs("li", { className: css.listItem, children: ["Database of recipes that can be replenished", " "] }), _jsx("li", { className: css.listItem, children: "Flexible search for desired and unwanted ingredients" }), _jsx("li", { className: css.listItem, children: "Ability to add your own recipes with photos" }), _jsx("li", { className: css.listItem, children: "Convenient and easy to use" })] })] }), _jsx("nav", { className: css.footerNav, children: _jsx(Nav, {}) }), _jsxs("div", { className: css.subscribeBox, children: [_jsxs("div", { className: css.box, children: [_jsx("p", { className: css.subscribeTitle, children: "Subscribe to our Newsletter" }), _jsx("p", { className: css.subscribeDesc, children: "Subscribe up to our newsletter. Be in touch with latest news and special offers, etc." })] }), _jsx(SubscribeForm, {})] })] }), _jsx(FollowUs, {})] }) }))] })) }));
};
export default Footer;
